plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'

Layout/LineLength:
  Max: 110

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'spec/**/*.rb'

RSpec/ExampleLength:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
